### ISSUE TITLE
World Quests at top of quest log not being respected

### ISSUE THREAD

**Issue by cikichen** [GurliGebis/WoWAddon-AngrierWorldQuests#101]
#74 I had the same issue and found that it conflicts with PetTracker. When PetTracker is enabled, the list cannot be displayed.https://www.curseforge.com/wow/addons/pettracker

**Comment by GurliGebis** [comment]
PetTracker is broken, and it normally takes quiet a while for him to fix it.
Please see #97 - instead, I have created a alternative to PetTracker, called Battle Pet Completionist.
I cannot workaround another addon breaking things due to not being updated.
