### ISSUE TITLE
Unable to auto-fill in groupfinder quests

### ISSUE THREAD

**Issue by glyneth** [GurliGebis/WoWAddon-AngrierWorldQuests#21]
This started around 9.1.5 I believe, but it may have been earlier. When using Angrier World Quests and Group finder, it is no longer auto-filling the information on the quest into the finder when I select the button and then Start a Group. It's defaulting to Raids, Sanctum of Domination or Castle Nathria, and Title is blank as are the details. If I turn off AWQ, then it will auto-fill in the details just fine, whether it's an elite quest or a raid quest.

**Comment by GurliGebis** [comment]
Can you paste a copy of the error it shows? (If you install addons like BugGrabber and BugSack, they make it easy to get the errors logged and then copied).

**Comment by glyneth** [comment]
There's no error message; it just doesn't autofill in the details of the
world quest. I could send screenshots, but I don't know they'd be of any
use.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GurliGebis** [comment]
I just tried again with 10.1, when I click the green eye button, and then click "Start a Group", it just starts it, with the WQ info.
So I'm not able to reproduce the problem.
I'll close the ticket, please let me know if it is still an issue, and if so, please record a video of the issue and link it here.
