### ISSUE TITLE
Suggestion: Add configuration option to display this addon's world quest stuff in a tab on world map

### ISSUE THREAD

**Issue by Knaledge** [GurliGebis/WoWAddon-AngrierWorldQuests#25]
Akin to the no longer maintained [World Quest Tab](https://www.curseforge.com/wow/addons/worldquesttab) addon (authored by [LanceDH](https://lancedh.github.io/) [[github](https://github.com/LanceDH)]), it would be fantastic to see your addon inherit even the slightest ember from that torch by allowing users to configure how world quests are displayed. In other words, your addon does what it does to world quests - and this feature request asks you to consider allowing users to move all of that into a new tab. 

This will further enhance organization while also catering to the (many) users coming from WQT that no longer have an addon that (in some way) facilitates a "mode switch" (so to speak) whereby a player can log in to focus on standard quests - or "switch modes" to world quests by changing the tab they are focusing on. If it seems simple, I hope it ends up being the case in the code! 

I will owe you a pizza. Either way, keep up the great work!

**Comment by GurliGebis** [comment]
I had a look at it - doing this would require a complete rewrite (more or less), and would move away from the idea of this addon being as close to the official UI as possible.
A better way would be for someone to take up the other addon, and maintain it going forward.
