### ISSUE TITLE
Add Dragonflight factions to filter

### ISSUE THREAD

**Issue by xanagear** [GurliGebis/WoWAddon-AngrierWorldQuests#27]
Easily the best world quest addon and I really appreciate you keeping it updated! Looks like the faction filter is still only showing shadowlands factions. 

Thank you for your work!!!

**Comment by GurliGebis** [comment]
I will, but I haven't yet gotten any of my own characters to unlock WQs

**Comment by Uberlicious** [comment]
I have opened a pull request to add the 10.0 factions in.

**Comment by GurliGebis** [comment]
> I have opened a pull request to add the 10.0 factions in.

Thank you, I have pushed a new version with your changes :)
