### ISSUE TITLE
Issue in Dungeon

### ISSUE THREAD

**Issue by darbiirue** [GurliGebis/WoWAddon-AngrierWorldQuests#28]
This particular error started as soon as I went into a Dragonflight Dungeon for the first time. It resulted in WoW automatically forcing me to disable the addon altogether.

`1x [ADDON_ACTION_BLOCKED] AddOn 'AngrierWorldQuests' tried to call the protected function 'MultiBarBottomLeftButton8:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:910: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:264: in function <FrameXML/ActionButton.lua:256>`

**Comment by GurliGebis** [comment]
The problem is not with this addon, please see #24
