### ISSUE TITLE
LUA error:  ADDON_ACTION_BLOCKED] AddOn 'AngrierWorldQuests' tried to call the protected function 'MainMenuBar:SetPointBase()'.

### ISSUE THREAD

**Issue by Benflag** [GurliGebis/WoWAddon-AngrierWorldQuests#29]
2x [ADDON_ACTION_BLOCKED] AddOn 'AngrierWorldQuests' tried to call the protected function 'MainMenuBar:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:72: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:623: in function <FrameXML/EditModeManager.lua:607>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:676: in function `UpdateGridLayout'
[string "@FrameXML/ActionButton.lua"]:368: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

**Comment by GurliGebis** [comment]
This is not caused by this addon, see the explanation in here: #24
