### ISSUE TITLE
Lua Errors w/ Angrier World Quests enabled

### ISSUE THREAD

**Issue by Kev1112005** [GurliGebis/WoWAddon-AngrierWorldQuests#30]
I'm receiving Lua errors, reported by BugSack/BugGrabber:

4x [ADDON_ACTION_BLOCKED] AddOn 'AngrierWorldQuests' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:72: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:628: in function <FrameXML/EditModeManager.lua:607>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:676: in function `UpdateGridLayout'
[string "@FrameXML/ActionButton.lua"]:368: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

**Comment by GurliGebis** [comment]
Hey,

This is not related to this addon, please see the explanation in #24
