### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Rezy942** [GurliGebis/WoWAddon-AngrierWorldQuests#35]
Hello,

Thank you for maintaining this addon!

Feature 1) I would love a feature to disable quest log integration entirely, and only leave world map icons feature enabled.
With dragonflight especially, world quests are not as important and many, so I'd like to free up quest log space and have less things running for simplistic & immersive experience. All I need is to see world quests on the world map.

Feature 2) Related to above feature - I would like an >option< to reskin the world map WQ icons to show the reward type. For example gold rewards = gold icon. And so on. It would be a bit more useful compared to default icons, while still being minimal.

Lastly a question - what is this feature?
I toggled it on and off and was never able to understand what it does. Do you think it should be re-worded?
![image](https://user-images.githubusercontent.com/122007087/212522125-9a55255c-04d4-4640-a9f5-7b66e0a9f793.png)

Thank you!!

**Comment by JBabbb** [comment]
I agree on this big time! 

Would be amazing to have two options:
1. For those who love the verbose style (detailed quest log info + all other features), 
2. Those who want a minimal experience (i.e., just icons showing on the continent & zone maps with reskinning of the WQ icons)

**Comment by Rezy942** [comment]
To expand on this - since DF launch and how easy they made these quests - quest log WQ's have become somewhat pointless.
I actually NEVER open my WQ quest log anymore, compared to expac's like legion or BFA or even Shadowlands.

So indeed, map icons with reward icon would be fantastic... ty

**Comment by arctikstorm** [comment]
I came here to ask exactly for the same thing. The addon "Better World Quests" does change the map icons to the respective reward type, but it has too many conflicts with your add-on...

So my request would be to add the functionality, or look into compatibility with the mentioned add-on.

**Comment by GurliGebis** [comment]
1: I'll see what I can do, but it might take a while though.
2: I have taken a look at it, from what I can see, it requires quiet a lot of chances, so again, it might take a while, and I cannot promise anything. (I know Better World Quests does this, but the license they use prevents me from using anything from there).

The "Always show hovered World Quest POI icon" shows the quest symbol on the map when you hover over it in the list to the right. (So if only tracked WQs are visible, and this one is enabled, they show up temporarily if you hover over them in the list).

If anyone is able to help with this, I would be more than happy to accept pull requests 🙂

**Comment by Rezy942** [comment]
Thank you for taking the time to reply.
After looking at improved world quests addon I actually decided to switch as that is what im looking for. (didnt know it existed).
I still like the world quest list in quest log option to go along with that addon but as it stands now there are conflicts.
I will revisit the addon if you ever decide to implement these features :)

Cheers

**Comment by GurliGebis** [comment]
1: Has been implemented in v0.40.6 that I just pushed.
In the settings dialog, select "Hide World Quests in the quest log" and they will no longer be shown in the quest log.
The other one is still going to take a while.

**Comment by JBabbb** [comment]
Don't stress too much if you cannot get the icons showing!

I say this because when I tried 'Better World Quests', it was showing the incorrect location for some of the WQ's which made the addon unusable for me.

**Comment by Rezy942** [comment]
I did notice that their addon also throws up errors when using handynotes. Definetely far from being perfect.
Also thanks GurliGebis appreciate that!!! will try out

**Comment by GurliGebis** [comment]
Handynotes can be difficult for other addons to coexist with, from what I have heard 🙂
