### ISSUE TITLE
Error after patch 10.1

### ISSUE THREAD

**Issue by jleafey** [GurliGebis/WoWAddon-AngrierWorldQuests#39]
The quest frame appears at the right of my Map & Quest Log frame, but BugGrabber has captured the following exception, which seems to be caught again whenever I move my mouse over certain parts of the frame:

18x AngrierWorldQuests/QuestFrame.lua:598: attempt to index global 'QUEST_TAG_TCOORDS' (a nil value)
[string "@AngrierWorldQuests/QuestFrame.lua"]:598: in function <AngrierWorldQuests/QuestFrame.lua:547>
[string "@AngrierWorldQuests/QuestFrame.lua"]:1056: in function <AngrierWorldQuests/QuestFrame.lua:939>
[string "=[C]"]: in function `QuestLogQuests_Update'
[string "@FrameXML/QuestMapFrame.lua"]:565: in function `QuestMapFrame_UpdateAll'
[string "@FrameXML/QuestMapFrame.lua"]:34: in function `Refresh'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:161: in function `RefreshQuestLog'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:233: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:230>
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua"]:331: in function `GoToMap'
[string "@Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua"]:389: in function `myclick'
[string "@FrameXML/NavigationBar.lua"]:181: in function <FrameXML/NavigationBar.lua:171>

Locals:
questInfo = <table> {
 mapID = 2022
 isCombatAllyQuest = false
 questId = 66419
 y = 0.349779
 x = 0.415568
 numObjectives = 1
 isQuestStart = false
 childDepth = 1
 inProgress = false
 isDaily = false
}
button = Button {
 0 = <userdata>
 TagText = FontString {
 }
 TimeIcon = Texture {
 }
 worldQuest = true
 infoY = 0.349779
 mapID = 2022
 Text = FontString {
 }
 TagTexture = Texture {
 }
 factionID = 2510
 ButtonText = FontString {
 }
 Check = Texture {
 }
 numObjectives = 1
 questID = 66419
 GetButtonType = <function> defined @FrameXML/QuestMapFrame.lua:1710
 awq = true
 TaskIcon = Texture {
 }
 infoX = 0.415568
}
questID = 66419
title = "Allegiance to One"
factionID = 2510
capped = false
questTagInfo = <table> {
 quality = 0
 isElite = true
 worldQuestType = 2
 tagID = 111
 displayExpiration = true
 tagName = "Elite World Quest"
}
tradeskillLineID = nil
timeLeftMinutes = nil
totalHeight = 20.000001
difficultyColor = <table> {
 b = 0
 font = "QuestDifficulty_Difficult"
 g = 0.820000
 r = 1
}
hasIcon = true
(*temporary) = nil
(*temporary) = 85
(*temporary) = 0.080000
(*temporary) = 0.920000
(*temporary) = 0.080000
(*temporary) = 0.920000
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'QUEST_TAG_TCOORDS' (a nil value)"
titleFramePool = <table> {
 frameType = "BUTTON"
 ReleaseAll = <function> defined @SharedXML/Pools.lua:140
 activeObjects = <table> {
 }
 GetNextInactive = <function> defined @SharedXML/Pools.lua:158
 creationFunc = <function> defined @SharedXML/Pools.lua:182
 EnumerateActive = <function> defined @SharedXML/Pools.lua:150
 SetResetDisallowedIfNew = <function> defined @SharedXML/Pools.lua:146
 GetTemplate = <function> defined @SharedXML/Pools.lua:219
 OnLoad = <function> defined @SharedXML/Pools.lua:190
 frameTemplate = "QuestLogTitleTemplate"
 IsActive = <function> defined @SharedXML/Pools.lua:162
 GetNumActive = <function> defined @SharedXML/Pools.lua:166
 resetterFunc = <function> defined @SharedXML/Pools.lua:227
 parent = Frame {
 }
 numActiveObjects = 1
 inactiveObjects = <table> {
 }
 Release = <function> defined @SharedXML/Pools.lua:125
 Acquire = <function> defined @SharedXML/Pools.lua:106
 GetNextActive = <function> defined @SharedXML/Pools.lua:154
 EnumerateInactive = <function> defined @SharedXML/Pools.lua:170
}
TitleButton_Initiliaze = <function> defined @AngrierWorldQuests/QuestFrame.lua:511
TitleButton_RarityColorTable = <table> {
 0 = 0
 2 = 10
 1 = 3
}
CURRENCYID_WAR_SUPPLIES = 1342
CURRENCYID_NETHERSHARD = 1226
CURRENCYID_AZERITE = 1553
Addon = <table> {
 RegisterAddOnLoaded = <function> defined @AngrierWorldQuests/Core.lua:59
 RegisterEvent = <function> defined @AngrierWorldQuests/Core.lua:18
 NewModule = <function> defined @AngrierWorldQuests/Core.lua:110
 ForAllModules = <function> defined @AngrierWorldQuests/Core.lua:119
 Modules = <table> {
 }
 Version = "v0.40.7"
 Name = "Angrier World Quests"
 PLAYER_ENTERING_WORLD = <function> defined @AngrierWorldQuests/Core.lua:128
 UnregisterAddOnLoaded = <function> defined @AngrierWorldQuests/Core.lua:77
 ADDON_LOADED = <function> defined @AngrierWorldQuests/Core.lua:47
 UnregisterEvent = <function> defined @AngrierWorldQuests/Core.lua:28
 ModulePrototype = <table> {
 }
}
ANIMA_ITEM_COLOR = <table> {
 b = 1
 g = 0.800000
 r = 0.600000
}
GetAnimaValue = <function> defined @AngrierWorldQuests/QuestFrame.lua:155

**Comment by Rezy942** [comment]
Yep same, getting spammed, had to disable addon for now. Hopefully an easy fix! :)

**Comment by GurliGebis** [comment]
Yep, I got it as well, I'm working on a fix for it.
Expect a new release later today (EU time)

**Comment by GurliGebis** [comment]
I have pushed v0.41.0 now, it should show up soon (whenever curseforge decides to push it to users)

**Comment by Rezy942** [comment]
Works like a charm, thanks a bunch for being so quick!!!!

**Comment by GurliGebis** [comment]
@Rezy942 you're very welcome, though the patch was provided by @sehra 🙂
