### ISSUE TITLE
Nonstop errors preventing use of quest objective "skill icons"

### ISSUE THREAD

**Issue by Rezy942** [GurliGebis/WoWAddon-AngrierWorldQuests#41]
Officially fed up with this. Has been an issue probably for at least a year now.
I commend your great work to keep this addon going, but for an addon so painfully barebone and feature-void, it is the buggiest one out of many others with millions lines of code.
Unfortunate have to delete. Probably wont be using any WQ addon as there are no good alternatives.

Errors like these - most likely combat related:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:95: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:88>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by GurliGebis** [comment]
Well, the function it mentions `UseQuestLogSpecialItem` is not called from this addon.
The problem with the way Blizzard has implemented addons is that one addon can break something, and then when another addon tries to use it, it crashes and the error points to that addon as the problem.

Since the function mentioned isn't being called from this addon (do a search for it in the files included with the addon if you want to verify it for yourself).

So some other addon on your system is breaking stuff, causing AWQ to crash with the above error.

**Comment by Rezy942** [comment]
Fair enough - although at this point this addon is the biggest culprit even though it's supposed to be other addon's fault.
Its easier just to get rid of it tbh.
Out of curiousity - why does this addon interact with questlogspecialitem in the first place? 
I would imagine all this addon should be doing is simply reading the WQ data and outputting the information. Why does it try to modify any blizz frames in the first place? Is this all just to have that "quest log" visual integration?

**Comment by GurliGebis** [comment]
It doesn't use the special item api's, so it doesn't seem to be the cause of it.
It has to integrate with the quest log frame, so it has to modify that one.

**Comment by Rezy942** [comment]
I see. So perhaps the reason im not having this many issues with other WQ addons is that they dont try to interact with blizzard frames, but instead build their own frames to output the info. I hope that makes sense. So you could say this bug is not caused by this addon, but the way it's built into the blizz frames causes unnecessary headaches by forcing user to /reload constantly once other addons act up. Either way, thank you for your insight! :)

**Comment by GurliGebis** [comment]
That is the way I understand it, yes.
Since this is an addon I have taken over, I mostly maintain it to keep it working, instead of rewriting too much, since there is a risk of breaking everything in the process 😊
