### ISSUE TITLE
Item comparison tooltip - strange interaction

### ISSUE THREAD

**Issue by JBabbb** [GurliGebis/WoWAddon-AngrierWorldQuests#44]
Hello,

I've noticed when attempting to compare items in the quest log, if you mouse over and then press SHIFT it will not show the item comparison tooltip. However, if you hold SHIFT prior to mousing over the item, it will show the item comparison tooltip as intended.

Thank you for this addon :)

**Comment by GurliGebis** [comment]
Hey,

I can reproduce it easily, but from what I can see, it isn't something I can easily change.
The logic triggering the display of the comparison window is the default Blizzard logic, so unless I'm missing something, it isn't something I can change.

Please let me know, if you (or anyone else), know how this could be changed.
Thanks for reporting the issue though 🙂
