### ISSUE TITLE
World quests with no rewards show a reward

### ISSUE THREAD

**Issue by jungheeMW** [GurliGebis/WoWAddon-AngrierWorldQuests#48]
In the following pic, Allegiance to One has no reward, but it will show as having one by Angrier World Quests

<img width="683" alt="better pic" src="https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/assets/134947146/810835e5-906b-4eef-8122-a704003fba13">

**Comment by GurliGebis** [comment]
Thank you, I'll look into it 🙂

**Comment by jungheeMW** [comment]
Thank you.
