### ISSUE TITLE
Lua error with TWW prepatch

### ISSUE THREAD

**Issue by KatyPurry** [GurliGebis/WoWAddon-AngrierWorldQuests#49]
Hello, I got a lua error with TWW prepatch (addon version v0.42.8)

```
Message: Interface/AddOns/AngrierWorldQuests/Config.lua:461: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Time: Wed Jul 24 09:27:31 2024
Count: 1
Stack: Interface/AddOns/AngrierWorldQuests/Config.lua:461: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Interface/AddOns/AngrierWorldQuests/Config.lua"]:461: in function `CreatePanel'
[string "@Interface/AddOns/AngrierWorldQuests/Config.lua"]:528: in function `?'
[string "@Interface/AddOns/AngrierWorldQuests/Core.lua"]:122: in function `ForAllModules'
[string "@Interface/AddOns/AngrierWorldQuests/Core.lua"]:130: in function `?'
[string "@Interface/AddOns/AngrierWorldQuests/Core.lua"]:10: in function <Interface/AddOns/AngrierWorldQuests/Core.lua:6>

Locals: self = <table> {
}
panel = Frame {
 name = "Angrier World Quests"
}
(*temporary) = nil
(*temporary) = Frame {
 name = "Angrier World Quests"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
Addon = <table> {
 Modules = <table> {
 }
 Version = "v0.42.8"
 Name = "Angrier World Quests"
 ModulePrototype = <table> {
 }
}
```

**Comment by GurliGebis** [comment]
I am working on getting it fixed.
11.0.0 broken several things, so it takes a while to get around it all. (they rewrote the quest log)

**Comment by KatyPurry** [comment]
No problem, thank you for your answer and good luck for !

**Comment by ynazar1** [comment]
Excitedly waiting for this to be hopefully fixed. 

Super quick question. Was it THIS addon that was popping up the world quests to the overall expansion map? I can see quests in zones but not once I zoom out. I was sure that it was default feature but even with every addon disabled it's not there. I'm trying to figure out now if this changed in pre-patch or it was some addon that was doing it and is currently non-functional.

**Comment by GurliGebis** [comment]
It sounds like it yes.
The problem now is that they have changed the quest log around, so I need to figure out how to add data to it, without breaking anything 🙂

**Comment by ynazar1** [comment]
Yeah that's tricky and good luck. The new quest list looks like a pie of frames. LUA is always messy to code in. :( 

Temporary solution: I found [world quest list](https://www.curseforge.com/wow/addons/world-quests-list) ... It seems more convoluted vs AWQ which i love for its simplicity.... But with some tweaking to the options it's mostly a passable stopgap.

**Comment by karpana** [comment]
> It sounds like it yes. The problem now is that they have changed the quest log around, so I need to figure out how to add data to it, without breaking anything 🙂

@GurliGebis 
I see you carved off a branch to do some TWW work.
Do let us know if there anything we can help with (e.g. testing or similar).

**Comment by GurliGebis** [comment]
@karpana I will - right now I just managed to silence the errors it throw when trying to set up the options page.
Another problem I'm trying to find a solution to, is now Blizzard has their own WQ filter for the map - so maybe we should integrate into that (if possible, doesn't look easy).

So there are several issues that needs to be fixed.

**Comment by GurliGebis** [comment]
I have pushed an update (v0.42.9) which prevents the addon from throwing errors when it is loaded.
It is not ready for TWW (yet), but this at least prevents it from crashing stuff 🙂

**Comment by Hayato2846** [comment]
> I have pushed an update (v0.42.9) which prevents the addon from throwing errors when it is loaded. It is not ready for TWW (yet), but this at least prevents it from crashing stuff 🙂

Sadly, can't confirm that. Getting following error with latest version:

```
1x AngrierWorldQuests/QuestFrame.lua:1259: hooksecurefunc(): OnSelection is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@AngrierWorldQuests/QuestFrame.lua"]:1259: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:63: in function `RegisterAddOnLoaded'
[string "@AngrierWorldQuests/Core.lua"]:102: in function `RegisterAddOnLoaded'
[string "@AngrierWorldQuests/QuestFrame.lua"]:1285: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:122: in function `ForAllModules'
[string "@AngrierWorldQuests/Core.lua"]:130: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:10: in function <AngrierWorldQuests/Core.lua:6>

Locals:
```

Thanks for your hard work!

**Comment by karpana** [comment]
Super Excited @GurliGebis !!!
I see a new version in CurseForge!

SQUEE!

**Comment by karpana** [comment]
@GurliGebis 
alas, looks like blizz made some surprise changes that weren't on the PTR yesterday....

```lua
7x AngrierWorldQuests/Core.lua:136: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@AngrierWorldQuests/Core.lua"]:136: in main chunk

Locals:
ADDON = "AngrierWorldQuests"
Addon = <table> {
 Modules = <table> {
 }
 ModulePrototype = <table> {
 }
}
Listener = AngrierWorldQuestsListener {
}
EventListeners = <table> {
 PLAYER_ENTERING_WORLD = <table> {
 }
}
AddOnListeners = <table> {
}
ModulePrototype = <table> {
}
(*temporary) = nil
(*temporary) = "AngrierWorldQuests"
(*temporary) = "Title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

```

**Comment by ynazar1** [comment]
That was coming... change to: `C_AddOns.GetAddOnMetadata`

Or better yet add in the beginning of the file that errors as needed:
```
local IsAddOnLoaded = C_AddOns.IsAddOnLoaded
local GetAddOnMetadata = C_AddOns.GetAddOnMetadata
```

**Comment by Gnarfoz** [comment]
> @GurliGebis alas, looks like blizz made some surprise changes that weren't on the PTR yesterday....
GetAddOnMetadata was deprecated in patch 10.1.0, over a year ago (May 2023). ;-)

It was just gated behind the deprecation CVar:
https://warcraft.wiki.gg/wiki/CVar_loadDeprecationFallbacks
https://github.com/Gethe/wow-ui-source/tree/11.0.0/Interface/AddOns/Blizzard_Deprecated

Addon developers should really test their addons after setting this CVar.

**Comment by GurliGebis** [comment]
Several of my repos started having issues with the github action upload of releases.
So since the zip file can be downloaded from curseforge the same way as here, I choose to keep it simple and focus on the addons instead of infrastructure 🙂

**Comment by AcidWeb** [comment]
In this case I would like to respectfully request other source than CF. If not GH then Wago - you already have pipeline in place to release it there too.

**Comment by GurliGebis** [comment]
I don't remember how it was failing.
Can you explain what the problem with CF is? (It is quiet easy to just go there and click Download)

**Comment by AcidWeb** [comment]
It is owned by Overwolf. It is a slimy company and some people don't want to support their business.

**Comment by Gnarfoz** [comment]
Looking at [a random other addon](https://github.com/icbat/broker-dungeon-difficulty/blob/main/.github/workflows/release.yml), it seems like the only thing you'd need to add would be the access token. Everything else seems to be in place.

**Comment by jleafey** [comment]
Loaded up v0.42.10 from CurseForge and noted I was not seeing the display.  BugGrabber offered me this:

```
14x AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AngrierWorldQuests/QuestFrame.lua"]:556: in function <AngrierWorldQuests/QuestFrame.lua:548>
[string "@AngrierWorldQuests/QuestFrame.lua"]:586: in function <AngrierWorldQuests/QuestFrame.lua:584>
[string "@AngrierWorldQuests/QuestFrame.lua"]:1100: in function <AngrierWorldQuests/QuestFrame.lua:979>
[string "=[C]"]: in function `QuestLogQuests_Update'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:869: in function `QuestMapFrame_UpdateAll'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:227: in function `Refresh'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:164: in function `RefreshQuestLog'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:305: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:302>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua"]:492: in function `GoToMap'
[string "@Blizzard_WorldMap/Blizzard_WorldMapTemplates.lua"]:550: in function `myclick'
[string "@Blizzard_FrameXML/Mainline/NavigationBar.lua"]:172: in function <Blizzard_FrameXML/Mainline/NavigationBar.lua:162>

Locals:
(*temporary) = Texture {
}
(*temporary) = "TOP"
(*temporary) = FontString {
}
(*temporary) = "CENTER"
(*temporary) = 0
(*temporary) = 8
```

**_Cannot anchor to a region dependent on it_** sounds like something else might have gotten greedy?

**Comment by GurliGebis** [comment]
I'll look into other hosting as well, once we get this one in a working state (doing it while it doesn't work makes no sense).
@jleafey Thank you for your report 🙂 - right now the addon is broken (I'm working on fixing it - the last few releases has been to make sure it doesn't break the game if it is enabled)

**Comment by jleafey** [comment]
I code a bit myself, but I am a tyro with Lua, and the WoW API has
impressed me with its breadth and rate of change! I fixed a couple of
add-ons myself by checking the docs online, and where they made more
functions subordinate to classes it was relatively easy to fix. However,
without a lot of study I get out of my depth quickly. Thanks for giving us
a great addon!

**Comment by GurliGebis** [comment]
Any help is appreciated.
I have some ideas of how it might be possible to integrate into the quest log - hopefully I can get to test them soon 🙂

**Comment by Shauren** [comment]
#53

**Comment by GurliGebis** [comment]
@Shauren Thank you, I have merged your fixes 🙂
@jleafey , @KatyPurry , @Gnarfoz , @karpana - can you all try out `v0.43.0` (should be available shortly) and see if it works for you as well.
Closing ticket, please reopen if it doesn't work.

**Comment by Gnarfoz** [comment]
Excellent work, @Shauren! This was the one addon that was still on my "broken since 11.0" list. ❤️
