### ISSUE TITLE
Error upon opening world map (Retail build using v0.42.10 dated 8/14/2024)

### ISSUE THREAD

**Issue by schwanzLutschen** [GurliGebis/WoWAddon-AngrierWorldQuests#51]
116x AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AngrierWorldQuests/QuestFrame.lua"]:556: in function <AngrierWorldQuests/QuestFrame.lua:548>
[string "@AngrierWorldQuests/QuestFrame.lua"]:586: in function <AngrierWorldQuests/QuestFrame.lua:584>
[string "@AngrierWorldQuests/QuestFrame.lua"]:1100: in function <AngrierWorldQuests/QuestFrame.lua:979>
[string "=[C]"]: in function `QuestLogQuests_Update'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:869: in function `QuestMapFrame_UpdateAll'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:507: in function <...ns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua:474>
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:518: in function <...ns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua:515>

Locals:
(*temporary) = Texture {
}
(*temporary) = "TOP"
(*temporary) = FontString {
}
(*temporary) = "CENTER"
(*temporary) = 0
(*temporary) = 8

**Comment by bubfeeld** [comment]
fyi, after making the addon_metadata and isaddonloaded changes in the previous release .42.9, this error does not appear

**Comment by GurliGebis** [comment]
Okay, so the error doesn't show anymore?

**Comment by Rav99** [comment]
This error is still there.

**Comment by bubfeeld** [comment]
> Okay, so the error doesn't show anymore?

i was kind of confusing, i had updated to the same version as the OP, (.42.10) and i got the same error, since I didnt remember getting it prior to updating from version .42.9, i reinstalled 42.09 and made the changes above and no longer got the error, however I did get another one, that was likely one you fixed funny enough,lol. Ill edit this post an add it

**Comment by bubfeeld** [comment]
9x AngrierWorldQuests/QuestFrame.lua:1259: hooksecurefunc(): OnSelection is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@AngrierWorldQuests/QuestFrame.lua"]:1259: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:63: in function `RegisterAddOnLoaded'
[string "@AngrierWorldQuests/Core.lua"]:102: in function `RegisterAddOnLoaded'
[string "@AngrierWorldQuests/QuestFrame.lua"]:1285: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:122: in function `ForAllModules'
[string "@AngrierWorldQuests/Core.lua"]:130: in function `?'
[string "@AngrierWorldQuests/Core.lua"]:10: in function <AngrierWorldQuests/Core.lua:6>

**Comment by GurliGebis** [comment]
I have pushed `v0.42.11` which hopefully should stop these errors, while I work on a new version that works with TWW 🙂

Please reopen if the issue still persists after.
