### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by Mike160770** [GurliGebis/WoWAddon-AngrierWorldQuests#52]
Message: Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
Time: Tue Aug 20 00:37:28 2024
Count: 1
Stack: Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:556: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:548>
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:586: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:584>
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:1100: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:979>
[string "=[C]"]: in function `QuestLogQuests_Update'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:869: in function `QuestMapFrame_UpdateAll'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:227: in function `Refresh'
[string "@Interface/AddOns/Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:164: in function `RefreshQuestLog'
[string "@Interface/AddOns/Blizzard_WorldMap/Blizzard_WorldMap.lua"]:305: in function `OnMapChanged'
[string "@Interface/AddOns/Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Interface/AddOns/Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:814: in function `NavigateToCursor'
[string "@Interface/AddOns/Blizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua"]:111: in function <...lizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua:102>

Locals: button = Button {
 Checkbox = Frame {
 }
 StorylineTexture = Texture {
 }
 TagTexture = Texture {
 }
 ButtonText = FontString {
 }
 HighlightTexture = Texture {
 }
 Text = FontString {
 }
 TaskIcon = Texture {
 }
}

**Comment by Mike160770** [comment]
Message: Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
Time: Tue Aug 20 00:38:27 2024
Count: 3
Stack: Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:556: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: Texture:SetPoint.
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:556: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:548>
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:586: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:584>
[string "@Interface/AddOns/AngrierWorldQuests/QuestFrame.lua"]:1100: in function <Interface/AddOns/AngrierWorldQuests/QuestFrame.lua:979>
[string "=[C]"]: in function `QuestLogQuests_Update'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:869: in function `QuestMapFrame_UpdateAll'
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:507: in function <...ns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua:474>
[string "@Interface/AddOns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:518: in function <...ns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua:515>

Locals: button = Button {
 Checkbox = Frame {

**Comment by GurliGebis** [comment]
I have pushed `v0.42.11` which hopefully should stop these errors, while I work on a new version that works with TWW 🙂

Please reopen if the issue still persists after.

**Comment by Mike160770** [comment]
> I have pushed `v0.42.11` which hopefully should stop these errors, while I work on a new version that works with TWW 🙂
> 
> Please reopen if the issue still persists after.

now it is completely broken... it does not load or I am too dumb to activate it on the map - no button or something similar

**Comment by GurliGebis** [comment]
It is broken - the current changes are just to make sure it doesn't break anything else.
It is not compatible with TWW yet, so all the changes I'm making now it to make sure it doesn't break everything else.
