### ISSUE TITLE
No function anymore

### ISSUE THREAD

**Issue by Mike160770** [GurliGebis/WoWAddon-AngrierWorldQuests#54]
Since the latest update now it is completely broken... it does not load or I am too dumb to activate it on the map - no button or something similar

**Comment by Shauren** [comment]
Feel free to try #53

**Comment by GurliGebis** [comment]
@Mike160770 can you please try `v0.43.0` and reopen if there are still issues?

**Comment by Mike160770** [comment]
A lot better now - some issues still here --> see #55 and #56
