### ISSUE TITLE
Clicking on AWQ in quest log misaligns it

### ISSUE THREAD

**Issue by ynazar1** [GurliGebis/WoWAddon-AngrierWorldQuests#55]
AWQ 0.43
WoW 11.0.2

Clicking on the title of the world quest misaligns it in the frames... I'm going to test it some more but here's what it looking like: 

![image](https://github.com/user-attachments/assets/dedd2a6c-95e8-4213-a48f-6ccce174f417)

**Comment by ynazar1** [comment]
Can confirm this happens even if AWQ is the only addon enabled.

**Comment by GurliGebis** [comment]
@Shauren do you happen to have an idea of why it happens?

**Comment by Shauren** [comment]
Yes, default mouseup/mousedown handlers of blizz QuestLogTitleTemplate expect the button to have two separate anchors (QuestMapLogTitleButton_OnMouseDown/QuestMapLogTitleButton_OnMouseUp)

**Comment by GurliGebis** [comment]
I have just pushed `v0.43.1` with the bugfixes from Shauren - please test and reopen if the issue persists.
