### ISSUE TITLE
Wrong display of pet battle rewards

### ISSUE THREAD

**Issue by tau-rho** [GurliGebis/WoWAddon-AngrierWorldQuests#56]
Hi,

with v0.43.0, when tracking pet battle WQs there seems to be an issue with the display of the rewards, for instance:

- bandages: WQs with as, e.g., 15 or 18 as reward only show as 10 for each in the quest log
- charms: WQs with >10 charms only appear as 1
- training stone: all rewards appear as 1

![2024-08-22-211442_498x267_scrot](https://github.com/user-attachments/assets/7542e669-1a76-40fa-bb2b-d57dbe871a79)

**Comment by GurliGebis** [comment]
I have just pushed `v0.43.1` with the bugfixes from Shauren - please test and reopen if the issue persists.
