### ISSUE TITLE
Feature Request: Evaluate more items into groups that aren't grouped now

### ISSUE THREAD

**Issue by ynazar1** [GurliGebis/WoWAddon-AngrierWorldQuests#60]
Related to #56 but not pet charms this time around.

Suffusion Camp rewards shows icon but not the amount of rep for sorting. 

Request: 
Evaluate some of the items to group them together if possible. 

Ie: 
* Reputation tokens with reputation 
* Pet stones with pet charms

![image](https://github.com/user-attachments/assets/a1f43e8f-5e8b-43da-bb46-64eb583b3ac8)

**Comment by ynazar1** [comment]
I just realized that technically it's working as intended because it's an item so it falls under 'other'.

**Comment by GurliGebis** [comment]
I'll take a look at it and see what data I can get from the api 🙂

**Comment by GurliGebis** [comment]
It doesn't look like I can do this easily - so it isn't something I'll be looking more into right now at least.
The problem is, that if we have to sort like this, we have to do a lot of lookups and custom logic for each quest, which will slow down the UI quiet a bit.
