### ISSUE TITLE
Feature Request: Indication on world quest not completed by warband

### ISSUE THREAD

**Issue by Zaazu** [GurliGebis/WoWAddon-AngrierWorldQuests#62]
Since the release of the Warband feature, world quests now offer a bonus the first time you complete them. I think it would be nice if there was some way to easily see which world quests have already been completed by a character.

![image](https://github.com/user-attachments/assets/bb55343b-9269-48eb-8dc9-a7fa6c127ec3)

I was thinking either use an underline to show that world quest has not been completed yet:
![1](https://github.com/user-attachments/assets/912c0fce-6070-45f3-bb02-acd693b150f1)

or desaturated text for world quests that have been completed:
![2](https://github.com/user-attachments/assets/452fbaf6-659d-43b4-aae6-506fa1a941d6)

**Comment by GurliGebis** [comment]
I like your idea 🙂
I will see if there is a way to query if there is a bonus for a WQ

**Comment by GurliGebis** [comment]
I have unlocked world quests now - but I cannot find any with this message on them.
Also, from what I can see, it looks like you might be able to query if quest has this bonus enabled (Haven't been able to find it yet, but it should be there).
However, I fear that once that has been completed on a WQ, it just appears to the system as if it didn't have a bonus at all. (Like there is no difference between quests without a bonus and quests that had a bonus but has been completed)

**Comment by Zaazu** [comment]
The world map must be getting that info from somewhere.

World Map: 
![image](https://github.com/user-attachments/assets/dd823858-5b54-496a-9b7d-e5882d1bf6a6)

Angrier World Quests:
![image](https://github.com/user-attachments/assets/1f3964d5-d1e4-44d2-a7dd-dc5ecec39d7e)

**Comment by CruelDrool** [comment]
Try adding this in [Modules/QuestFrame/QuestFrameModule.lua, on line 414](https://github.com/GurliGebis/WoWAddon-AngrierWorldQuests/blob/main/Modules/QuestFrame/QuestFrameModule.lua#L414):
```lua
button.questRewardTooltipStyle = TOOLTIP_QUEST_REWARDS_STYLE_WORLD_QUEST
```

**Comment by GurliGebis** [comment]
Okay, that works, and it also pointed me in the right direction `C_QuestLog.QuestContainsFirstTimeRepBonusForPlayer` 🙂
However, I still have two problems (please let me know if you have any ideas):

1: WQs before TWW does not have bonus, so they all return false, which would color them as well - any ideas on how to avoid that?
2: Not all WQs has a bonus - so they would be grey, even if they have never been completed - there doesn't seem to be a way to detect this.

I'll release the change with the tooltip in the next release shortly, but the rest I don't know how to fix.

**Comment by Zaazu** [comment]
The warband bonus in tooltip was a good change, thanks. 
How about an extra icon showing the bonus next to the other rewards? Although, with the tooltip change it's not as needed anymore.

Quick Mockup:
![image](https://github.com/user-attachments/assets/b50fad5c-d6d8-49fe-b718-5a2207bd3693)

**Comment by GurliGebis** [comment]
How about coloring them with a different color, if there is a bonus?
That way, the reward text will still be aligned 🙂

**Comment by Zaazu** [comment]
Sounds good, there's already a red text world quest for something, a world boss I think.

**Comment by GurliGebis** [comment]
This is what I ended up with (reusing the same color as the "Awards...." text 🙂

![billede](https://github.com/user-attachments/assets/c1feb42c-5fd5-44fb-9b0b-ec585306334a)

**Comment by Zaazu** [comment]
Looking real nice 🙂

**Comment by GurliGebis** [comment]
I have just pushed `11.0.2-20240912-1` - if you install it, and then enable the option `Color World Quests with Warband bonus blue`, it should work 🙂
