### ISSUE TITLE
Disabling pet battles in blizzard tracker doesn't remove them from the map

### ISSUE THREAD

**Issue by cbossaers** [GurliGebis/WoWAddon-AngrierWorldQuests#65]
Disabling pet battles in blizzard tracker doesn't remove them from the "region map" (Khaz Algar in this case), despite being removed from the zone map (Isle of Dorn in the provided picture) and correctly disappearing from the questlog list. All other addons are disabled. This doesn't happen in other regions such as the Dragon Isles.

![Captura de pantalla 2024-08-27 214410](https://github.com/user-attachments/assets/f51ef4b6-8c50-4b99-9ad4-393a27daccb3)
![Captura de pantalla 2024-08-27 214426](https://github.com/user-attachments/assets/e3563952-d0b4-498c-9606-95ec067cd859)
![Captura de pantalla 2024-08-27 214528](https://github.com/user-attachments/assets/4007078e-f707-4cad-851d-b7f145c5f846)

**Comment by GurliGebis** [comment]
We override the entire filtering process, so you should not use the built-in filtering (it has no effect).

I'm looking into if there is a way to remove it from the menu.

**Comment by cbossaers** [comment]
So if I understand this correctly, there's no way to filter out pet battles with the addon?

**Comment by GurliGebis** [comment]
We are talking about pet battle world quests, correct?

**Comment by cbossaers** [comment]
Yes

**Comment by GurliGebis** [comment]
The build in world quest filters doesn't work while this addon is loaded (Since we override thr function that does the filtering)
I don't see a way those two could coexist, since they both filter the visible quests, but by using two completely different methods (if both where working at the same time, the result would be a mess)
