### ISSUE TITLE
World Quests at top of quest log not being respected

### ISSUE THREAD

**Issue by Adrenalined** [GurliGebis/WoWAddon-AngrierWorldQuests#74]
I have the option to show "World Quests at the top of quest log" but it isn't happening.

[Example here](https://imgur.com/a/OvCtnGJ)

**Comment by GurliGebis** [comment]
Interresting - it sounds like the logic to insert the list needs to be updated again.
I'll see if I can replicate it locally - can you attach a screenshot of your settings as well (makes it easier to make sure I have it set up the same way you do)

**Comment by Adrenalined** [comment]
Absolutely, I've attached below.  If I didn't get what you needed let me know, I can do more testing/uploading as needed.  Sorry for the delay, didn't get the notification on this.

[Updated screenshot for info](https://imgur.com/N3QMFo0)

**Comment by GurliGebis** [comment]
That's really strange - with my settings set the same way as yours, this is what I'm seeing:

![billede](https://github.com/user-attachments/assets/36fea638-0eaa-4986-b076-0800ec36871c)

**Comment by Adrenalined** [comment]
Will try to reproduce again, I had thought it was always like that.  I logged on the next day and it was fixed.  WIll need to figure out what triggered it.

**Comment by GurliGebis** [comment]
Okay - please reopen if you can reproduce it.
Could be something else messing with the quest list though (I always unload all other addons when debugging, since it makes it easier to see if the problem is with a specific addon, or something else)

**Comment by cikichen** [comment]
@GurliGebis I had the same issue and found that it conflicts with PetTracker. When PetTracker is enabled, the list cannot be displayed.https://www.curseforge.com/wow/addons/pettracker

**Comment by cikichen** [comment]
@Adrenalined

**Comment by GurliGebis** [comment]
PetTracker is broken, and it normally takes quiet a while for him to fix it.
Please see #97 - instead, I have created a alternative to PetTracker, called Battle Pet Completionist.
I cannot workaround another addon breaking things due to not being updated.
