### ISSUE TITLE
Request for correction of error

### ISSUE THREAD

**Issue by taraksoul** [GurliGebis/WoWAddon-AngrierWorldQuests#75]
Client language: Korean(Ko-KR)
Client version: 11.0.2

1x [ADDON_ACTION_BLOCKED] 애드온 'AngrierWorldQuests'|1이;가; 보호된 함수 'Frame:SetPropagateMouseClicks()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPropagateMouseClicks'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:459: in function `UpdateMousePropagation'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:464: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:555: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:52: in function `OnAcquired'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:204: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/DungeonEntranceDataProvider.lua"]:35: in function `RefreshAllData'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:476: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:475>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:479: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:474>
[string "=[C]"]: in function `RefreshAllDataProviders'
...
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:336: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:174: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:169>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:888: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:866>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:511: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:510>
[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

Errors occur frequently.

**Comment by GurliGebis** [comment]
Which version of the addon do you have installed?

**Comment by GurliGebis** [comment]
If you open options for the addon, and then enable the setting for `Enable taint workarounds` and see if that fixes the issue.
If the issue persists, please reopen the ticket.

**Comment by GurliGebis** [comment]
It seems like the worldmap taint isn't being patched.
Can you please attach a screenshot of your configuration dialog?

**Comment by GurliGebis** [comment]
Yep.

Put a check in the `Enable taint workarounds - Reloads UI (might have unknown effects)` checkbox, and then try again.
If the issue is still there, reopen the ticket.

**Comment by GurliGebis** [comment]
It enables some workarounds for issues with Blizzards code, that prevents the addon from doing what it wants to do (like manipulate the icons on the map and tracking world quests)

**Comment by GurliGebis** [comment]
That should be fixed in the latest release.
Please try with that, with all other addons disabled (just to confirms nothing else is causing the issue)

**Comment by GurliGebis** [comment]
Yep, which is why I'm pretty certain it is not this addon causing it, if the workarounds are enabled.

Every issue we have had with taints, it has been a question about tracking and untracking world quests, followed by another action which then crashe.

Normally, when playing, this addon doesn't do anything (after all, its purpose is to have a list of world quests in the quest log).
