### ISSUE TITLE
attempt to index field 'Modules' (a nil value)

### ISSUE THREAD

**Issue by Quartzfire** [GurliGebis/WoWAddon-AngrierWorldQuests#76]
Good Evening,

I get the following LUA during loading of the game.

4x ...ernal/AngrierWorldQuests/Core.AngrierWorldQuests.lua:15: attempt to index field 'Modules' (a nil value)
[string "@CaerdonWardrobe/external/AngrierWorldQuests/Core.AngrierWorldQuests.lua"]:15: in function `Init'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:1060: in function `handler'
[string "@CaerdonWardrobe/CaerdonWardrobe.lua"]:1005: in function <CaerdonWardrobe/CaerdonWardrobe.lua:1002>

Locals:
self = <table> {
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = true
 baseName = "AngrierWorldQuests"
 Version = "11.0.2-20240910-2"
 Name = "Angrier World Quests"
 defaultModuleState = true
 name = "AngrierWorldQuests"
 orderedModules = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Modules' (a nil value)"
addonName = "AngrierWorldQuests"
isHooked = false

**Comment by GurliGebis** [comment]
Hey,

The bug is in CaerdonWardrobe, it has an integration to Angrier World Quests, but hasn't been updated to the new, rewrite version.
Please report a bug report with the here instead 🙂
https://github.com/Caerdon/CaerdonWardrobe/issues

**Comment by Quartzfire** [comment]
Hi,

Thanks for your quick response.

I've raised ticket for CaerdonWardrobe: https://github.com/Caerdon/CaerdonWardrobe/issues/48

Thanks,
Quartz
