### ISSUE TITLE
SortMethod error

### ISSUE THREAD

**Issue by glyneth** [GurliGebis/WoWAddon-AngrierWorldQuests#77]
When scrolling over the dropdown arrow for Sort By, I get the following error. I am using version: 11.0.2-20240912-2

`Message: ...rWorldQuests/Modules/QuestFrame/QuestFrameModule.lua:206: attempt to concatenate local 'sortMethod' (a nil value)
Time: Wed Oct  2 12:28:35 2024
Count: 4
Stack: ...rWorldQuests/Modules/QuestFrame/QuestFrameModule.lua:206: attempt to concatenate local 'sortMethod' (a nil value)
[string "@Interface/AddOns/AngrierWorldQuests/Modules/QuestFrame/QuestFrameModule.lua"]:206: in function <...rWorldQuests/Modules/QuestFrame/QuestFrameModule.lua:177>

Locals: self = Button {
 filter = "SORT"
}
text = "Sort By"
filterEmissary = 0
filterLoot = 0
lootFilterUpgrades = false
filterFaction = 0
sortMethod = nil
(*temporary) = <table> {
 config_showHoveredPOI = "Always show hovered World Quest POI icon"
 config_lootUpgradesLevel = "Loot filter shows upgrades"
 config_onlyCurrentZone = "Only show World Quests for the current zone"
 config_saveFilters = "Save active filters between logins"
 config_showAtTop = "Display at the top of the Quest Log"
 config_hideUntrackedPOI = "Hide untracked World Quest POI icons on the world map"
 config_lootUpgradesLevelValue1 = "Higher ilvl only"
 config_sortMethod = "Sort World Quests by"
 config_lootUpgradesLevelValue = "Up to %d ilvls less"
 config_enableTaintWorkarounds = "Enable taint workarounds - Reloads UI (might have unknown effects)"
 UPGRADES = "Upgrades"
 config_lootFilterUpgrades = "Show only upgrades for Loot filter"
 config_sortMethod_4 = "Faction"
 config_lootUpgradesLevelValue2 = "Up to same ilvl"
 config_showContinentPOI = "Show World Quest POI icons on continent maps"
 config_sortMethod_5 = "Rewards"
 config_enabledFilters = "Enabled Filters"
 config_timeFilterDuration = "Time Remaining filter duration"
 config_hideFilteredPOI = "Hide filtered World Quest POI icons on the world map"
 CONDUIT_ITEMS = "Conduit items"
 config_sortMethod_2 = "Time Left"
 config_sortMethod_3 = "Zone"
 config_enableDebugging = "Enable debugging (requires DebugLog addon installed)"
 config_hideQuestList = "Hide World Quests in the quest log"
 CURRENT_ZONE = "Current Zone"
 config_sortMethod_1 = "Name"
 config_colorWarbandBonus = "Color World Quests with Warband bonus blue"
 config_characterConfig = "Per-character configuration"
}
(*temporary) = "config_sortMethod_"
(*temporary) = nil
(*temporary) = <table> {
 AceDB = <table> {
 }
 baseName = "AngrierWorldQuests"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = true
 moduleName = "DBModule"
 defaultModuleState = true
 name = "AngrierWorldQuests_DBModule"
 orderedModules = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 AceDB = <table> {
 }
 baseName = "AngrierWorldQuests"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = true
 moduleName = "DBModule"
 defaultModuleState = true
 name = "AngrierWorldQuests_DBModule"
 orderedModules = <table> {
 }
}
(*temporary) = <table> {
 filterFaction = 0
 filterTime = 0
 extendedInfo = "false"
 disabledFilters = 16314953
 hideUntrackedPOI = "false"
 selectedFilters = 0
 saveFilters = "false"
 showContinentPOI = "true"
 timeFilterDuration = 6
 lootFilterUpgrades = "false"
 showHoveredPOI = "false"
 dataVersion = 2
 colorWarbandBonus = "false"
 filterEmissary = 0
 hideQuestList = "false"
 enableDebugging = "false"
 showAtTop = "true"
 hideFilteredPOI = "true"
 filterLoot = 0
 filterZone = 0
 sortMethod = 1
 enableTaintWorkarounds = "false"
 onlyCurrentZone = "true"
 collapsed = false
 lootUpgradesLevel = -1
}
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'sortMethod' (a nil value)"
ConfigModule = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 FiltersOrder = <table> {
 }
 name = "AngrierWorldQuests_ConfigModule"
 orderedModules = <table> {
 }
 baseName = "AngrierWorldQuests"
 Filters = <table> {
 }
 enabledState = true
 defaultModuleState = true
 SortOrder = <table> {
 }
 moduleName = "ConfigModule"
}
L = <table> {
 config_showHoveredPOI = "Always show hovered World Quest POI icon"
 config_lo`

**Comment by GurliGebis** [comment]
Thanks, I'll take a look at it 🙂

**Comment by GurliGebis** [comment]
I have pushed `11.0.2-20241003-1` with a fix for this issue 🙂
