### ISSUE TITLE
Cosmetic issue when quest log is empty

### ISSUE THREAD

**Issue by kaldonir** [GurliGebis/WoWAddon-AngrierWorldQuests#81]
When the quest log is empty, the official UI shows "No quests available - Accept quests by talking to characters with a ! above their head."

This interferes with the list of world quests:

![](https://github.com/user-attachments/assets/43d6c696-39d3-4b26-aca5-ffdf26fb73c9)

This text can be manually hidden / shown by calling `QuestScrollFrame.EmptyText:Hide()`, and `Show()` respectively.

I tried hooking `QuestScrollFrame.EmptyText:Hide()` to `AngrierWorldQuestsHeader`'s `OnShow` Event, but that didn't work. Any hints where I'd need to implement this? Then I can maybe open a PR.

**Comment by GurliGebis** [comment]
I will take a look at it 🙂

**Comment by GurliGebis** [comment]
I just pushed `11.0.2-20241008-1` which fixes the problem.
As a bonus - you can now use the search box at the top to search the world quest list as well.
