### ISSUE TITLE
Error when trying to use items from Objective Frame

### ISSUE THREAD

**Issue by JargerWolf** [GurliGebis/WoWAddon-AngrierWorldQuests#86]
I am getting the following error anytime I try to use items for quests from my objective frame:

2x [ADDON_ACTION_FORBIDDEN] AddOn 'AngrierWorldQuests' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

It will be fine for a little while after reload but then it stops working again after a bit... I am guessing it happens when I go through a load screen.

**Comment by GurliGebis** [comment]
Can you try and enable the addon setting that Adda workarounds for issues?
It is a checkbox inside the addon options dialog.
If the issue persists after that, please let me know, and I'll reopen the ticket 🙂

**Comment by JargerWolf** [comment]
Enable Taint workarounds was already enabled. Issue still happens with it checked :(

**Comment by GurliGebis** [comment]
Okay, can you tell what you where doing in game, when it happened?

**Comment by JargerWolf** [comment]
Nothing to specific unfortunately. It happens when I have a quest that requires me to use an item. For Example, the greater keyflame quest, The Midnight Sentry which requires you to use the Sentry Flare to "uncloak" mobs. If I try to use the item from my quest log, I get the error and have to use it from my bag. I can reload UI and it will work from the log again for some time but then eventually it stops working again and I continue to get the error. I suspect that it has something to do with loading screens but that is just my guess.

**Comment by GurliGebis** [comment]
I see.
We already have a thread going about this issue here: #59 
Please report in there, so we don't have multiple threads going about the same issue.

I'm looking into the issue, but I cannot promise anything yet.
