### ISSUE TITLE
World Quest header missing when tracking

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [GurliGebis/WoWAddon-AngrierWorldQuests#94]
When I track a faction, and I complete all of those world quests, the World Quest header in the quest log disappears. I can't stop tracking that faction anymore because the header and buttons are now gone. It takes a /reload to get it back.

**Comment by GurliGebis** [comment]
Can you attach a screenshot of it?

**Comment by GurliGebis** [comment]
Nevermind, I figured out what is causing it - new release incoming.

**Comment by GurliGebis** [comment]
I have pushed `11.0.5-20241030-1` which fixes the issue.
