### ISSUE TITLE
Repeated error message whenever the in-game map is open

### ISSUE THREAD

**Issue by nerolite** [GurliGebis/WoWAddon-AngrierWorldQuests#99]
As of the most recent patch, I receive the following repeated error message:
`498x Blizzard_POIButton/POIButton.xml:68 Frame Frame: Unknown script element OnClick`

when the following is true:
_**a)** The addon "Angrier World Quests"_ is enabled
and
_**b)** The Blizzard map setting: "Map Filter" > "World Quests"_ is enabled
and
_**c)** The in-game map is open_

Disabling any of the above stops the error message spam.

**Version:** 11.0.7.58187 (Siren Isle)
**Addon version:** 11.0.7-20241218-1

Is there anything that can be done to alleviate this and continue using the addon?

**Comment by GurliGebis** [comment]
I have just pushed version `11.0.7-20241220-1` - does it still happen with that version?
Also, have you tried with just AngrierWorldQuests enabled?

**Comment by nerolite** [comment]
@GurliGebis the new version resolved the issue. I no longer experience the error message. Thank you!

**Comment by GurliGebis** [comment]
You're welcome 😊
